resources:
  - name: myDockerRepo
    type: GitRepo
    configuration:
      gitProvider: myGitHub
      path: https://github.com/jagdishmirani/docker-build-example.git
    branches:
        include: master
 
  - name: build_info_1_docker_build_push
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryIntegration
      buildName: svc_build
      buildNumber: 1
      
pipelines:
  - name: pipeline_docker_build_push
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 'pipe-master.jfrog.info:8081/docker-local/alpine37'
          dockerImageTag: ${run_number}
          inputResources:
            - name: myDockerRepo
          integrations:
            - name: ArtifactoryIntegration
 
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dockerGroup
          targetRepository: docker-local
          integrations:
            - name: ArtifactoryIntegration
          inputSteps:
            - name: docker_build
 
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: build_info_1_docker_build_push
